import type {
	IHookFunctions,
	IWebhookFunctions,
	IDataObject,
	INodeType,
	INodeTypeDescription,
	IWebhookResponseData,
	IHttpRequestOptions,
} from 'n8n-workflow';
import { createHash, timingSafeEqual } from 'node:crypto';
import { NodeOperationError } from 'n8n-workflow';
import { isValidIvantiGuid } from './common';


/**
 * Trigger node that receives inbound webhook calls from Ivanti Neurons for ITSM
 * automation runbooks.
 *
 * ## How it works
 * 1. An Ivanti automation runbook is configured to POST a JSON payload to the
 *    n8n webhook URL generated by this node.
 * 2. The node validates:
 *    - `Content-Type` must be `application/json`
 *    - `X-Workflow-Id` header must match the current n8n workflow ID (prevents
 *      cross-workflow replay attacks)
 *    - Authorization header must match the configured
 *      `ivantiNeuronsForItsmConnectorAuthApi` credential
 *      (Basic Auth, API key, or custom header token)
 *    - `X-Transaction-Id` header must be present and exactly 32 characters (Ivanti GUID format)
 *    - Transaction must be in a valid state (not Completed, Failed, or Aborted)
 *    - All user-defined required parameters are  resent and have the correct type
 * 3. On success the node responds `200 OK` and passes the request body downstream.
 * 4. On any validation failure it responds `400` with the error message and stops
 *    the workflow execution for that request.
 *
 * ## Webhook lifecycle
 * Webhook registration is fully managed by n8n; `checkExists`, `create`, and
 * `delete` all return `true` without making external API calls.
 */
export class IvantiNeuronsForItsmConnectorTrigger implements INodeType {
	description: INodeTypeDescription = {
		displayName: 'Ivanti Neurons for ITSM Connector Trigger',
		usableAsTool: true,
		name: 'ivantiNeuronsForItsmConnectorTrigger',
		icon: { light: 'file:../../icons/synergy.svg', dark: 'file:../../icons/synergy.dark.svg' },
		group: ['trigger'],
		version: 1,
		subtitle: '=Updates: {{$parameter["updates"]}}',
		description: 'Receive webhook calls from Ivanti Neurons for ITSM automation jobs.The custom solution is required n8n package to be installed on the Ivanti instance. Please contact us at https://www.synergy.eu/',
		defaults: {
			name: 'Ivanti Neurons for ITSM Connector Trigger',
		},
		inputs: [],
		outputs: ['main'],
		credentials: [
			{
				name: 'ivantiNeuronsForItsmConnectorAuthApi',
				required: true,
			},
		],
		webhooks: [
			{
				name: 'default',
				httpMethod: 'POST',
				responseMode: 'onReceived',
				path: 'webhook',
			},
		],
		properties: [
			{
				displayName: 'Trigger On',
				name: 'updates',
				type: 'multiOptions',

				options: [
					{ name: 'On Automation Transaction', value: 'OnAutomationTransaction' },
				],
				default: ['OnAutomationTransaction'],

			},
			{
				displayName: 'Runbook Name',
				name: 'name',
				type: 'string',
				default: '',
				required: true,
				placeholder: 'My Runbook',
				description: 'The name of the runbook that will trigger this webhook',
			},
			{
				displayName: 'Input Parameters',
				name: 'parameters',
				type: 'fixedCollection',
				default: {},
				placeholder: 'Add Parameter',
				description: 'Define the expected parameters from the webhook request. Each parameter will be validated when the webhook is triggered.',
				typeOptions: {
					multipleValues: true,
				},
				options: [
					{
						displayName: 'Parameter',
						name: 'inputParameters',
						values: [
							{
								displayName: 'Name',
								name: 'name',
								type: 'string',
								default: '',
								required: true,
								description: 'The name of the parameter expected in the webhook payload. This is the name of the parameter that will be used in the webhook payload.',
							},
							{
								displayName: 'Type',
								name: 'type',
								type: 'options',
								default: 'string',
								required: true,
								description: 'The expected data type of this parameter',
								options: [
									{
										name: 'Boolean',
										value: 'boolean',
									},
									{
										name: 'DateTime',
										value: 'datetime',
									},
									{
										name: 'JSON',
										value: 'json',
									},
									{
										name: 'Number',
										value: 'number',
									},
									{
										name: 'String',
										value: 'string',
									},
								],
							},
							{
								displayName: 'Required',
								name: 'required',
								type: 'boolean',
								default: true,
								description: 'Whether the parameter is required',
							},
						],
					},
				],
			}
		],
	};
	webhookMethods = {
		default: {
			async checkExists(this: IHookFunctions): Promise<boolean> {
				// Webhook lifecycle is managed entirely by n8n
				return true;
			},
			async create(this: IHookFunctions): Promise<boolean> {
				// Webhook lifecycle is managed entirely by n8n
				return true;
			},
			async delete(this: IHookFunctions): Promise<boolean> {
				// Webhook lifecycle is managed entirely by n8n
				return true;
			},
		},
	};

	/**
	 * Handles an inbound POST request from an Ivanti automation runbook.
	 *
	 * Validates content-type, workflow-id header, authentication, and all
	 * user-defined parameter constraints before passing the body downstream.
	 * Responds synchronously (`onReceived`) so Ivanti receives an immediate
	 * acknowledgement without waiting for the rest of the workflow to finish.
	 */
	async webhook(this: IWebhookFunctions): Promise<IWebhookResponseData> {
		const resp = this.getResponseObject();
		const bodyData = this.getBodyData();

		try {
			const headers = this.getHeaderData();
			if (headers['content-type'] !== 'application/json') {
				throw new NodeOperationError(this.getNode(), 'Invalid Content-Type, expected application/json');
			}
			const workflowId = this.getWorkflow().id;
			if (headers['x-workflow-id'] !== workflowId) {
				throw new NodeOperationError(this.getNode(), 'Invalid Workflow ID');
			}

			await validateRequestAuth.call(this, headers);
			await validateAutomationTransaction.call(this, headers);
			validateParameters.call(this, bodyData);

			const transactionId = headers['x-transaction-id'] as string;
			bodyData["TransactionId"] = transactionId;

			resp.writeHead(200, { 'Content-Type': 'application/json' });
			resp.end(
				JSON.stringify({
					Status: 'Success',
					Message: 'Workflow started',
				}),
			);
			return {
				noWebhookResponse: true,
				workflowData: [this.helpers.returnJsonArray([bodyData as IDataObject])],
			};
		} catch (error) {
			if (error instanceof NodeOperationError) {

				resp.writeHead(400, {
					'WWW-Authenticate': 'Basic realm="Webhook"',
					'Content-Type': 'application/json'
				});
				resp.end(JSON.stringify({
					Status: 'Error',
					Message: error.message,
				}));
				return { noWebhookResponse: true };
			}
			throw error;
		}
	}
}


/**
 * Validates that the webhook request body contains all parameters declared in
 * the node's "Input Parameters" collection and that each value matches its
 * declared type.
 *
 * Type checking rules:
 * - `string`   → must be a JS string
 * - `number`   → must be a JS number
 * - `boolean`  → must be a JS boolean
 * - `datetime` → must be a string (ISO 8601 format expected by Ivanti)
 * - `json`     → must be a string (serialised JSON, not a parsed object)
 *
 * Optional parameters (not marked `required`) that are absent from the body
 * are silently skipped — type checking only runs when a value is present.
 */
function validateParameters(this: IWebhookFunctions, bodyData: IDataObject): boolean {
	if (typeof bodyData !== 'object' || bodyData === null) {
		throw new NodeOperationError(this.getNode(), 'Invalid JSON Body');
	}
	// Reads the user-configured parameter definitions from the node UI
	const parameters = this.getNodeParameter('parameters.inputParameters', []) as Array<{
		name: string;
		type: string;
		required: boolean;
	}>;
	for (const parameter of parameters) {
		const value = (bodyData as IDataObject)[parameter.name];
		if (parameter.required && value === undefined) {
			throw new NodeOperationError(this.getNode(), `Parameter ${parameter.name} is required`);
		}
		// Skip optional parameters that were not sent in the request
		if (value === undefined) {
			continue;
		}
		// datetime and json are transmitted as strings; their internal format is
		// not validated here — Ivanti enforces that on its side
		if (parameter.type === 'string' && typeof value !== 'string') {
			throw new NodeOperationError(this.getNode(), `Parameter ${parameter.name} must be a string`);
		} else if (parameter.type === 'number' && typeof value !== 'number') {
			throw new NodeOperationError(this.getNode(), `Parameter ${parameter.name} must be a number`);
		} else if (parameter.type === 'boolean' && typeof value !== 'boolean') {
			throw new NodeOperationError(this.getNode(), `Parameter ${parameter.name} must be a boolean`);
		} else if (parameter.type === 'datetime' && typeof value !== 'string') {
			throw new NodeOperationError(this.getNode(),
				`Parameter ${parameter.name} must be a datetime string`,
			);
		} else if (parameter.type === 'json' && typeof value !== 'string') {
			throw new NodeOperationError(this.getNode(), `Parameter ${parameter.name} must be a JSON string`);
		}
	}
	return true;
}
/**
 * Validates the `Authorization` header of an inbound webhook request against
 * the configured `ivantiNeuronsForItsmConnectorAuthApi` credential.
 *
 * Supports three authentication modes (selected by the credential's `type` field):
 * - **base**   – HTTP Basic Auth (`Basic <base64(username:password)>`)
 * - **apiKey** – the `Authorization` header must equal the configured `webhookApiKey`
 * - **header** – a custom header (named by `header`) must equal the configured `webhookApiKey`
 *
 * @throws {NodeOperationError} when credentials are missing, the auth type is
 *   unrecognised, or the header does not match
 */
async function validateRequestAuth(this: IWebhookFunctions, headers: IDataObject): Promise<boolean> {
	const credentials = await this.getCredentials('ivantiNeuronsForItsmConnectorAuthApi');
	if (credentials.type === 'base') {
		const encodedAuth = encodeBasicAuth(credentials.username as string, credentials.password as string);
		const provided = String(headers['authorization'] ?? '');
		if (!safeCompare(provided, `Basic ${encodedAuth}`)) {
			throw new NodeOperationError(this.getNode(), 'Invalid Authorization');
		}
	} else if (credentials.type === 'apiKey') {
		const provided = String(headers['authorization'] ?? '');
		if (!safeCompare(provided, `${credentials.webhookApiKey}`)) {
			throw new NodeOperationError(this.getNode(), 'Invalid Authorization');
		}
	} else if (credentials.type === 'header') {
		const headerName = ((credentials.header as string) ?? '').trim().toLowerCase();
		if (headerName === '') {
			throw new NodeOperationError(this.getNode(), 'Header auth is selected but no Header Name is configured');
		}
		// n8n returns header keys already lowercased, so look up with a lowercased name.
		const headerValue = headers[headerName];
		if (!headerValue) {
			throw new NodeOperationError(this.getNode(), 'Invalid Authorization');
		}
		if (headerValue !== credentials.webhookApiKey) {
			throw new NodeOperationError(this.getNode(), 'Invalid Authorization');
		}
	} else {
		throw new NodeOperationError(this.getNode(), 'Invalid Authorization Type');
	}
	return true;
}
/**
 * Validates an incoming automation transaction from Ivanti before the webhook payload is processed.
 *
 * Performs two layers of validation:
 * 1. Header check — ensures `x-transaction-id` is present and exactly 32 characters (Ivanti GUID format).
 * 2. Live status check — fetches the transaction record from the Ivanti OData API and rejects it
 *    if it is already in a terminal state (Completed / Failed / Aborted), preventing duplicate processing.
 *
 * On-prem instances require the `/HEAT` path segment in the base URL, which is derived from credentials.
 */
async function validateAutomationTransaction(this: IWebhookFunctions, headers: IDataObject): Promise<boolean> {
	if (headers['x-transaction-id'] === undefined) {
		throw new NodeOperationError(this.getNode(), 'Transaction ID is required');
	}
	if (headers['x-transaction-id'] === '') {
		throw new NodeOperationError(this.getNode(), 'Transaction ID is required');
	}
	// Ivanti transaction IDs are 32-character GUIDs (no hyphens)
	if (!isValidIvantiGuid(headers['x-transaction-id'])) {
		throw new NodeOperationError(this.getNode(), 'Transaction ID is not a valid GUID');
	}
	const credentials = await this.getCredentials('ivantiNeuronsForItsmConnectorAuthApi');
	if (credentials === undefined) {
		throw new NodeOperationError(this.getNode(), 'No credentials got returned!');
	}
	const tenant = credentials.tenant as string;
	const isOnPrem = credentials.isOnPrem as boolean;
	const skipSslVerification = credentials.skipSslVerification as boolean;
	// On-prem deployments expose the API under the /HEAT virtual directory
	const baseUrl = `https://${tenant}${isOnPrem ? '/HEAT' : ""}/api`;
	const transactionId = headers['x-transaction-id'];
	const url = `${baseUrl}/odata/businessobject/IVNT_Automation_Transactionss('${transactionId}')`; const options: IHttpRequestOptions = {
		method: 'GET',
		url: url,
		json: false,
		skipSslCertificateValidation: skipSslVerification,
	};
	const transaction = await this.helpers.httpRequestWithAuthentication.call(this, 'ivantiNeuronsForItsmConnectorAuthApi', options) as IDataObject;
	// Reject transactions that have already reached a terminal state to avoid reprocessing
	if (transaction["Status"] === "Completed" || transaction["Status"] === "Failed" || transaction["Status"] === "Aborted") {
		throw new NodeOperationError(this.getNode(), 'Transaction is already completed or failed or aborted');
	}
	return true;
}
function encodeBasicAuth(username: string, password: string): string {
	return Buffer.from(`${username}:${password}`).toString('base64');
}


/**
 * Constant-time string comparison.
 *
 * Both inputs are reduced to fixed-length SHA-256 digests before comparison so
 * that `timingSafeEqual` never sees mismatched buffer lengths (which would both
 * throw and leak the secret's length). This prevents a remote caller from using
 * response-timing differences to recover the configured webhook secret.
 */
function safeCompare(a: string, b: string): boolean {
	const aHash = createHash('sha256').update(a, 'utf8').digest();
	const bHash = createHash('sha256').update(b, 'utf8').digest();
	return timingSafeEqual(aHash, bHash);
}
